container:
  image: python:latest

test_task:

  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

  test_script: |
    set -x
    ls -l
    python3 -c 'import platform; print(platform.machine(), platform.uname())'
    python3 -m venv .venv
    source .venv/bin/activate
    python -m pip install .
    cd test
    python test1.py --output test1.pdf
    
        
  binaries_artifacts:
    path: test/*.pdf
